<a href="https://colab.research.google.com/github/bharathulaprasad/AprioriAlgorithm/blob/main/YetAnotherApriori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
dataset=[['Bread','Eggs','Butter'],
         ['Eggs', 'Bread', 'Milk'],
         ['Cheese', 'Chips'],
         ['Chips', 'Milk', 'Egg']]

## Assume we have condition of minimum support and minimum confidence condition of 0.5

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

In [4]:
dataset

[['Bread', 'Eggs', 'Butter'],
 ['Eggs', 'Bread', 'Milk'],
 ['Cheese', 'Chips'],
 ['Chips', 'Milk', 'Egg']]

In [5]:
te= TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)

In [6]:
df=pd.DataFrame(te_ary,columns=te.columns_)
df

   Bread  Butter  Cheese  Chips    Egg   Eggs   Milk
0   True    True   False  False  False   True  False
1   True   False   False  False  False   True   True
2  False   False    True   True  False  False  False
3  False   False   False   True   True  False   True

#Find frequent itemsets

In [7]:
from mlxtend import frequent_patterns
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(df,min_support=0.5,use_colnames=True)
frequent_itemsets

   support       itemsets
0      0.5        (Bread)
1      0.5        (Chips)
2      0.5         (Eggs)
3      0.5         (Milk)
4      0.5  (Bread, Eggs)

In [8]:
from mlxtend.frequent_patterns import association_rules
res = association_rules(frequent_itemsets,metric='confidence', min_threshold=0.50)
res

  antecedents consequents  antecedent support  ...  lift  leverage  conviction
0     (Bread)      (Eggs)                 0.5  ...   2.0      0.25         inf
1      (Eggs)     (Bread)                 0.5  ...   2.0      0.25         inf

[2 rows x 9 columns]